### ISSUE TITLE
changing corrugation size

### ISSUE THREAD

**Issue by Ahmed-Mohammad** [JonathanCauchon/Contra-DC#3]
When I read the thesis in theory folder, I saw that when designing the waveguides we need to set a corrugation height (Δw1). I am trying to change it corresponding with the design I made but didn't find any parameter. can you please tell me where can I change it in the code?

![image](https://user-images.githubusercontent.com/84653178/204220712-12bd577d-88f3-434b-9e03-e8a829e88767.png)

**Comment by JonathanCauchon** [comment]
Please refer to page 20 and Eq. 2.3 of said thesis. κ(z) is the parameter to use. It must be obtained from simulation or experimental. The litho smoothing must be taken into account and this is the reason it is not implemented using the corrugation sizes directly. 

[this tutorial](https://github.com/lukasc-ubc/SiEPIC_Photonics_Package/blob/master/SiEPIC_Photonics_Package/solvers_simulators/contraDC/Documentation/contraDC_Simulator.pdf) details several ways to extract kappa from the device geometry.

**Comment by Ahmed-Mohammad** [comment]
> Please refer to page 20 and Eq. 2.3 of said thesis. κ(z) is the parameter to use. It must be obtained from simulation or experimental. The litho smoothing must be taken into account and this is the reason it is not implemented using the corrugation sizes directly.
> 
> [this tutorial](https://github.com/lukasc-ubc/SiEPIC_Photonics_Package/blob/master/SiEPIC_Photonics_Package/solvers_simulators/contraDC/Documentation/contraDC_Simulator.pdf) details several ways to extract kappa from the device geometry.

Thank you for your help.


Another question, what is the pattern for the effective indices in neff.txt file? how can I replace them with the one I can get from Lumerical? and how many neff I need in the file to make it work? also, what is the content of polyfit.txt file? I didn't understand what is w1 coefficient 1, w1 coefficient 2, w2 coefficient 1, w2 coefficient 2? and how the second ones has negative values?
